CREATE TABLE SDB_USER(
    USE_ID NUMBER (3),
    USE_USER VARCHAR2(64),
    USE_EMAIL VARCHAR2(64),
    USE_PASSWORD VARCHAR2(64),
    CONSTRAINT PK_USE_ID PRIMARY KEY (USE_ID)
);

CREATE SEQUENCE SEQ_USE_ID START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_USER
MODIFY (USE_ID DEFAULT SEQ_USE_ID.NEXTVAL);

CREATE TABLE SDB_CUSTOMER(
    CUS_ID NUMBER (3),
    USE_ID NUMBER (3),
    CUS_EMAIL VARCHAR2(64),
    CUS_FIRST_NAME VARCHAR2(64),
    CUS_MIDDLE_NAME VARCHAR2(64),
    CUS_LAST_NAME VARCHAR2(64),
    CUS_SECONDLAST_NAME VARCHAR2(64),
    CUS_AFFILIATE NUMBER (15),
    CONSTRAINT PK_CUS_ID PRIMARY KEY (CUS_ID),
    CONSTRAINT USE_ID FOREIGN KEY (USE_ID) REFERENCES SDB_USER(USE_ID)
);

CREATE SEQUENCE SEQ_CUS_ID START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_CUSTOMER
MODIFY (CUS_ID DEFAULT SEQ_CUS_ID.NEXTVAL);

CREATE TABLE SDB_ADDRESS(
    DIR_ID NUMBER (3),
    CUS_ID NUMBER (3),
    DIR_FIRST_LINE NUMBER (5),
    DIR_SECOND_LINE NUMBER (5),
    DIR_RESIDENTIARY VARCHAR2(64),
    DIR_AVENUE VARCHAR2 (64),
    DIR_ZONE NUMBER (5),
    DIR_CITY VARCHAR2 (64),
    DIR_STATE VARCHAR2 (64),
    CONSTRAINT PK_DIR_ID PRIMARY KEY (DIR_ID),
    CONSTRAINT FK_CUS_ID FOREIGN KEY (CUS_ID) REFERENCES SDB_CUSTOMER(CUS_ID)
    );
    
CREATE SEQUENCE SEQ_DIR_ID START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_ADDRESS
MODIFY (DIR_ID DEFAULT SEQ_DIR_ID.NEXTVAL);

CREATE TABLE SDB_EMPLOYEE(
    EMP_ID NUMBER (3),
    USE_ID NUMBER (3),
    EMP_EMAIL VARCHAR2(64),
    EMP_HIREDATE DATE,
    EMP_FIRST_NAME VARCHAR2(64),
    EMP_MIDDLE_NAME VARCHAR2(64),
    EMP_LAST_NAME VARCHAR2(64),
    EMP_SECONDLAST_NAME VARCHAR2(64),
    EMP_FIRST_LINE NUMBER (5),
    EMP_SECOND_LINE NUMBER (5),
    EMP_RESIDENTIARY VARCHAR2(64),
    EMP_AVENUE VARCHAR2 (64),
    EMP_ZONE NUMBER (5),
    EMP_CITY VARCHAR2 (64),
    EMP_STATE VARCHAR2 (64),
    CONSTRAINT PK_EMP_ID PRIMARY KEY (EMP_ID),
    CONSTRAINT FK_USE_ID FOREIGN KEY (USE_ID) REFERENCES SDB_USER(USE_ID)
);

CREATE SEQUENCE SEQ_EMP_ID START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_EMPLOYEE
MODIFY (EMP_ID DEFAULT SEQ_EMP_ID.NEXTVAL);

Create Table SDB_SUPPLIER(
    SUP_ID Number(3),
    SUP_NIT Number(7), 
    SUP_SOCIAL_NAME Varchar2(20),
    SUP_NAME Varchar2(20),
    SUP_FIRST_LINE NUMBER (5),
    SUP_SECOND_LINE NUMBER (5),
    SUP_RESIDENTIARY VARCHAR2(64),
    SUP_AVENUE VARCHAR2 (64),
    SUP_ZONE NUMBER (5),
    SUP_CITY VARCHAR2 (64),
    SUP_STATE VARCHAR2 (64),
    Constraint PK_SUP_ID Primary Key (SUP_ID)
);

CREATE SEQUENCE seq_sup_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_SUPPLIER
MODIFY (SUP_ID DEFAULT seq_sup_id.nextval);

CREATE TABLE SDB_PRODUCT (
    PRO_ID Number(3) Null,
    PRO_NAME VARCHAR2(20),
    PRO_MEASUREMENT Number(2),
    PRO_QUANTITY Number(5),
    PRO_VALUE Number(5),
    PRO_DESCRIPTION Varchar2(30),
    Constraint PK_PRO_ID Primary Key (PRO_ID)
);

CREATE SEQUENCE seq_PRO_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_PRODUCT
MODIFY (PRO_ID DEFAULT seq_PRO_id.nextval);

Create Table SDB_PRODUCT_DETAIL(
    PRD_ID Number(3),
    PRO_ID Number(3),
    PRD_CATEGORY Number(2),
    PRD_CATEGORY_NAME Varchar2(20),
    PRD_MINIMUM_STOCK Number(1),
    Constraint PK_PRD_ID Primary Key (PRD_ID),
    Constraint FK_PRO_ID Foreign Key (PRO_ID) References SDB_PRODUCT(PRO_ID)
);

CREATE SEQUENCE seq_PRD_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_PRODUCT_DETAIL
MODIFY (PRD_ID DEFAULT seq_PRD_id.nextval);

Create Table SDB_DEPARTURE(
    DEP_ID Number(3),
    DEP_OUTDATE Date,
    DEP_ACTION Number(1),
    PRO_ID Number(3),
    DEP_MEASUREMENT Number(2),
    DEP_QUANTITY Number(2),
    DEP_VALUE Number(3),
    CUS_ID Number(3),
    Constraint PK_DEP_ID Primary Key (DEP_ID),
    Constraint FK_PROD_ID Foreign Key (PRO_ID) References SDB_PRODUCT(PRO_ID),
    Constraint FK_CUSS_ID Foreign Key (CUS_ID) References SDB_CUSTOMER(CUS_ID)
);

CREATE SEQUENCE seq_DEP_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_DEPARTURE
MODIFY (DEP_ID DEFAULT seq_DEP_id.nextval);

Create Table SDB_ENTRY(
    ENT_ID Number(3),
    ENT_ENTRYDATE Date,
    ENT_ACTION Number(1),
    PRO_ID Number(3),
    ENT_MEASUREMENT Number(2),
    ENT_QUANTITY Number(2),
    ENT_VALUE Number(3),
    SUP_ID Number(3),
    Constraint PK_ENT_ID Primary Key (ENT_ID),
    Constraint FK_PROE_ID Foreign Key (PRO_ID) References SDB_PRODUCT(PRO_ID),
    Constraint FK_SUPP_ID Foreign Key (SUP_ID) References SDB_SUPPLIER(SUP_ID)
);

CREATE SEQUENCE seq_ent_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_ENTRY
MODIFY (ENT_ID DEFAULT seq_ent_id.nextval);

Create Table SDB_ORDER(
    ORD_ID Number(3),
    ORD_ORDER_DATE TIMESTAMP(6),
    CLI_ID NUMBER (3),
    PRO_ID NUMBER(3),
    SER_ID NUMBER(3),
    ORD_QUANTITY Number(2),
    ORD_TOTAL NUMBER (6),
    Constraint PK_ORD_ID Primary Key (ORD_ID),
    Constraint FK_PROO_ID Foreign Key (PRO_ID) References SDB_PRODUCT(PRO_ID),
    Constraint FK_SER_ID Foreign Key (SER_ID) References SDB_SERVICE(SER_ID),
    Constraint FK_CLIO_ID Foreign Key (CLIO_ID) References SDB_CLIENT(CLI_ID)
);


CREATE SEQUENCE seq_ORD_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_ORDER
MODIFY (ORD_ID DEFAULT seq_ORD_id.nextval);

CREATE TABLE SDB_ORDER_DETAIL(
    ODE_ID NUMBER(3),
    ORD_ID NUMBER (3),
    ODE_DISCOUNT NUMBER(1),
    ODE_SUB_TOTAL NUMBER(10),
    CONSTRAINT PK_ODE_ID PRIMARY KEY (ODE_ID),
    CONSTRAINT CHECK_DISCOUNT CHECK (ODE_DISCOUNT IN (1,0))
);

CREATE SEQUENCE seq_ODE_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_ORDER_DETAIL
MODIFY (ODE_ID DEFAULT seq_ODE_id.nextval);

CREATE TABLE SDB_SERVICE(
    SER_ID NUMBER(3),
    SER_SERVICENAME NUMBER(1),
    SER_VALUE NUMBER(10),
    CONSTRAINT PK_SER_ID PRIMARY KEY (SER_ID)
);

CREATE SEQUENCE seq_SER_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_SERVICE
MODIFY (SER_ID DEFAULT seq_SER_id.nextval);

CREATE TABLE SDB_BILLING(
    BIL_ID NUMBER(3),
    ORD_ID NUMBER(3),
    BIL_SERIE VARCHAR2(10),
    BIL_NUMBER NUMBER(10),
    CONSTRAINT PK_BIL_ID PRIMARY KEY (BIL_ID),
    CONSTRAINT FK_ORDBI_ID FOREIGN KEY (ORD_ID) REFERENCES SDB_ORDER(ORD_ID)
);

CREATE SEQUENCE seq_BIL_id START WITH 1 INCREMENT BY 1;

ALTER TABLE SDB_BILLING
MODIFY (BIL_ID DEFAULT seq_BIL_id.nextval);