DELIMITER $$
/*
	AUDITORIA EMPLEADOS
*/
CREATE TRIGGER trg_employee_audit_insert 
AFTER INSERT ON SDB_EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'SDB_EMPLOYEE', 'INSERT');
END$$

CREATE TRIGGER trg_employee_audit_update 
AFTER UPDATE ON SDB_EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'SDB_EMPLOYEE', 'UPDATE');
END$$

CREATE TRIGGER trg_employee_audit_delete 
AFTER DELETE ON SDB_EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'SDB_EMPLOYEE', 'DELETE');
END$$

DELIMITER ;


DELIMITER $$
/*
	TRIGGER AUDITORIA CLIENTES SOLO UPDATE Y DELETE
*/
CREATE TRIGGER trg_CUSTOMER_audit_update 
AFTER UPDATE ON SDB_CUSTOMER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'CUSTOMER', 'UPDATE');
END$$

CREATE TRIGGER trg_CUSTOMER_audit_delete 
AFTER DELETE ON SDB_CUSTOMER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'SDB_CUSTOMER', 'DELETE');
END$$

DELIMITER ;

DELIMITER $$
/*
	TRIGGER AUDITORIA ADDRESS SOLO UPDATE Y DELETE
*/
CREATE TRIGGER trg_ADDRESS_audit_update 
AFTER UPDATE ON SDB_ADDRESS
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ADDRESS', 'UPDATE');
END$$

CREATE TRIGGER trg_ADDRESS_audit_delete 
AFTER DELETE ON SDB_ADDRESS
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ADDRESS', 'DELETE');
END$$

DELIMITER ;

DROP TRIGGER IF EXISTS TRG_ADDRESS_AUDIT_DELETE;

DELIMITER $$
/*
	ARREGLO A ELIMINACIÓN
*/
	CREATE TRIGGER TRG_ADDRESS_AUDIT_DELETE
    AFTER DELETE ON SDB_ADDRESS
    FOR EACH ROW
    BEGIN
		INSERT INTO SDB_AUDITABLE(AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
        VALUES (NOW(), CURRENT_USER(), 'ADDRESS', 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
/*
	REVIEW ELIMIINADAS
*/

	CREATE TRIGGER TRG_REVIEW_AUDIT_DELETE
    AFTER DELETE ON SDB_Review
    FOR EACH ROW
    BEGIN
		INSERT INTO SDB_AUDITABLE(AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
        VALUES (NOW(), CURRENT_USER(), 'REVIEW', 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
/*
	SERVICIOS ELIMINADOS
*/
	CREATE TRIGGER TRG_SERVICE_AUDIT_DELETE
    AFTER DELETE ON SDB_SERVICE
    FOR EACH ROW
    BEGIN
		INSERT INTO SDB_AUDITABLE(AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
        VALUES (NOW(), CURRENT_USER(), 'SERVICE', 'DELETE');
	END$$
DELIMITER ;

DELIMITER $$
/*
	AUDITORIA SUPPLIERS
*/
CREATE TRIGGER trg_SUPPLIER_audit_insert 
AFTER INSERT ON SDB_SUPPLIER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'SUPPLIER', 'INSERT');
END$$

CREATE TRIGGER trg_SUPPLIER_audit_update 
AFTER UPDATE ON SDB_SUPPLIER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'SUPPLIER', 'UPDATE');
END$$

CREATE TRIGGER trg_SUPPLIER_audit_delete 
AFTER DELETE ON SDB_SUPPLIER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'SUPPLIER', 'DELETE');
END$$

DELIMITER ;

DELIMITER $$
/*
	AUDITORIA USUARIOS
*/
CREATE TRIGGER trg_USER_audit_insert 
AFTER INSERT ON SDB_USER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'USER', 'INSERT');
END$$

CREATE TRIGGER trg_USER_audit_update 
AFTER UPDATE ON SDB_USER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'USER', 'UPDATE');
END$$

CREATE TRIGGER trg_USER_audit_delete 
AFTER DELETE ON SDB_USER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'USER', 'DELETE');
END$$

DELIMITER ;

DELIMITER $$
/*
	AUDITORIA PRODUCTOS
*/
CREATE TRIGGER trg_PRODUCT_audit_insert 
AFTER INSERT ON SDB_PRODUCT
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'PRODUCT', 'INSERT');
END$$

CREATE TRIGGER trg_PRODUCT_audit_update 
AFTER UPDATE ON SDB_PRODUCT
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'PRODUCT', 'UPDATE');
END$$

CREATE TRIGGER trg_PRODUCT_audit_delete 
AFTER DELETE ON SDB_PRODUCT
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'PRODUCT', 'DELETE');
END$$

DELIMITER ;

DELIMITER $$
/*
	TRIGGER AUDITORIA ORDENES SOLO UPDATE Y DELETE
*/
CREATE TRIGGER trg_ORDER_audit_update 
AFTER UPDATE ON SDB_ORDER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ORDER', 'UPDATE');
END$$

CREATE TRIGGER trg_ORDER_audit_delete 
AFTER DELETE ON SDB_ORDER
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ORDER', 'DELETE');
END$$

DELIMITER ;

DELIMITER $$
/*
	AUDITORIA ENTRADAS
*/
CREATE TRIGGER trg_ENTRY_audit_insert 
AFTER INSERT ON SDB_ENTRY
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ENTRY', 'INSERT');
END$$

CREATE TRIGGER trg_ENTRY_audit_update 
AFTER UPDATE ON SDB_ENTRY
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ENTRY', 'UPDATE');
END$$

CREATE TRIGGER trg_ENTRY_audit_delete 
AFTER DELETE ON SDB_ENTRY
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ENTRY', 'DELETE');
END$$

DELIMITER ;

DELIMITER $$
CREATE TRIGGER trg_ENTRY_audit_delete 
AFTER DELETE ON SDB_ENTRY
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'ENTRY', 'DELETE');
END$$

DELIMITER ; 

DELIMITER $$
/*
	AUDITORIA DEPARTURE
*/
CREATE TRIGGER trg_DEPARTURE_audit_insert 
AFTER INSERT ON SDB_DEPARTURE
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'DEPARTURE', 'INSERT');
END$$

CREATE TRIGGER trg_DEPARTURE_audit_update 
AFTER UPDATE ON SDB_DEPARTURE
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'DEPARTURE', 'UPDATE');
END$$

CREATE TRIGGER trg_DEPARTURE_audit_delete 
AFTER DELETE ON SDB_DEPARTURE
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'DEPARTURE', 'DELETE');
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER trg_DATE_audit_delete 
AFTER DELETE ON SDB_DATE
FOR EACH ROW
BEGIN
    INSERT INTO SDB_AUDITABLE (AUD_DATE, AUD_MODIFIED_BY, AUD_TABLE_AFFECTED, AUD_MOVE)
    VALUES (NOW(), CURRENT_USER(), 'DATE', 'DELETE');
END$$

DELIMITER ;